### ISSUE TITLE
Installation failed [Archlinux Wayland]

### ISSUE THREAD

**Issue by narisuzu** [yilozt/mutter-rounded#20]
failed in check()

```
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
# random seed: R02S792522f162f685d18680a67e4afa159a
# mutter-MESSAGE: Running Mutter Test (using mutter 41.2) as a Wayland display server
# mutter-MESSAGE: Added device '/dev/dri/renderD128' (nvidia-drm) using no mode setting.
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation memory (GMemorySettingsBackend) for ‘gsettings-backend’
# mutter-MESSAGE: Created gbm renderer for '/dev/dri/renderD128'
# mutter-MESSAGE: Boot VGA GPU /dev/dri/renderD128 selected as primary
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
# mutter-MESSAGE: Disabling DMA buffer screen sharing for driver 'nvidia-drm'.
# mutter-MESSAGE: Using Wayland display name 'mutter-test-display'
1..2
# Start of backends tests
# Start of native tests
# Start of virtual-monitor tests
# mutter-MESSAGE: Added virtual monitor Meta-0
Bail out! mutter-FATAL-ERROR: Failed to allocate back buffer texture: Failed to create an OpenGL framebuffer object
stderr:
mutter-Message: 05:11:44.697: Running Mutter Test (using mutter 41.2) as a Wayland display server
mutter-Message: 05:11:44.704: Added device '/dev/dri/renderD128' (nvidia-drm) using no mode setting.
mutter-Message: 05:11:44.725: Created gbm renderer for '/dev/dri/renderD128'
mutter-Message: 05:11:44.725: Boot VGA GPU /dev/dri/renderD128 selected as primary
mutter-Message: 05:11:44.739: Disabling DMA buffer screen sharing for driver 'nvidia-drm'.
mutter-Message: 05:11:44.739: Using Wayland display name 'mutter-test-display'
Window manager warning: Failed to set environment variable WAYLAND_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
mutter-Message: 05:11:44.744: Added virtual monitor Meta-0

(mutter-native-headless-tests:56261): mutter-ERROR **: 05:11:44.744: Failed to allocate back buffer texture: Failed to create an OpenGL framebuffer object
Traceback (most recent call last):
  File "/home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py", line 126, in <module>
    test_case.wrap_call(sys.argv[1:])
  File "/home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py", line 118, in wrap_call
    self.assertEqual(p.wait(), 0)
  File "/usr/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: -5 != 0
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[107/108] 🌕 mutter:core+mutter/ref-test/sanity / ref-test-sanity               [107/108] 🌖 mutter:core+mutter/ref-test/sanity / ref-test-sanity               107/108 mutter:core+mutter/ref-test/sanity / ref-test-sanity                                                    FAIL            0.77s   exit status 1
>>> G_TEST_BUILDDIR=/home/ling/.cache/paru/clone/mutter-rounded/src/build G_TEST_SRCDIR=/home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src MALLOC_PERTURB_=84 MUTTER_TEST_PLUGIN_PATH=/home/ling/.cache/paru/clone/mutter-rounded/src/build/src/compositor/plugins/libdefault.so /home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py /home/ling/.cache/paru/clone/mutter-rounded/src/build/src/tests/mutter-ref-test-sanity
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
# random seed: R02S1978fd87a8f67d7f6364363fe8d18aa5
# mutter-MESSAGE: Running Mutter Test (using mutter 41.2) as a Wayland display server
# mutter-MESSAGE: Added device '/dev/dri/renderD128' (nvidia-drm) using no mode setting.
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation memory (GMemorySettingsBackend) for ‘gsettings-backend’
# mutter-MESSAGE: Created gbm renderer for '/dev/dri/renderD128'
# mutter-MESSAGE: Boot VGA GPU /dev/dri/renderD128 selected as primary
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
# mutter-MESSAGE: Disabling DMA buffer screen sharing for driver 'nvidia-drm'.
# mutter-MESSAGE: Using Wayland display name 'mutter-test-display'
# mutter-MESSAGE: Added virtual monitor Meta-0
Bail out! mutter-FATAL-ERROR: Failed to allocate back buffer texture: Failed to create an OpenGL framebuffer object
stderr:
mutter-Message: 05:11:45.477: Running Mutter Test (using mutter 41.2) as a Wayland display server
mutter-Message: 05:11:45.484: Added device '/dev/dri/renderD128' (nvidia-drm) using no mode setting.
mutter-Message: 05:11:45.498: Created gbm renderer for '/dev/dri/renderD128'
mutter-Message: 05:11:45.498: Boot VGA GPU /dev/dri/renderD128 selected as primary
mutter-Message: 05:11:45.511: Disabling DMA buffer screen sharing for driver 'nvidia-drm'.
mutter-Message: 05:11:45.512: Using Wayland display name 'mutter-test-display'
Window manager warning: Failed to set environment variable WAYLAND_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
mutter-Message: 05:11:45.517: Added virtual monitor Meta-0

(mutter-ref-test-sanity:56294): mutter-ERROR **: 05:11:45.517: Failed to allocate back buffer texture: Failed to create an OpenGL framebuffer object
Traceback (most recent call last):
  File "/home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py", line 126, in <module>
    test_case.wrap_call(sys.argv[1:])
  File "/home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py", line 118, in wrap_call
    self.assertEqual(p.wait(), 0)
  File "/usr/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: -5 != 0
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[108/108] 🌗 mutter:core+mutter/native/persistent-virtual-monitor / native-persi[108/108] 🌘 mutter:core+mutter/native/persistent-virtual-monitor / native-persi108/108 mutter:core+mutter/native/persistent-virtual-monitor / native-persistent-virtual-monitor                FAIL            0.77s   exit status 1
>>> G_TEST_BUILDDIR=/home/ling/.cache/paru/clone/mutter-rounded/src/build G_TEST_SRCDIR=/home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src MALLOC_PERTURB_=197 MUTTER_TEST_PLUGIN_PATH=/home/ling/.cache/paru/clone/mutter-rounded/src/build/src/compositor/plugins/libdefault.so /home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py /home/ling/.cache/paru/clone/mutter-rounded/src/build/src/tests/mutter-persistent-virtual-monitor
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
mutter-Message: 05:11:46.250: Running Persistent virtual monitor test (using mutter 41.2) as a Wayland display server
mutter-Message: 05:11:46.257: Added device '/dev/dri/renderD128' (nvidia-drm) using no mode setting.
mutter-Message: 05:11:46.271: Created gbm renderer for '/dev/dri/renderD128'
mutter-Message: 05:11:46.271: Boot VGA GPU /dev/dri/renderD128 selected as primary
mutter-Message: 05:11:46.285: Disabling DMA buffer screen sharing for driver 'nvidia-drm'.
mutter-Message: 05:11:46.285: Added virtual monitor Meta-0

(mutter-persistent-virtual-monitor:56326): mutter-ERROR **: 05:11:46.286: Failed to allocate back buffer texture: Failed to create an OpenGL framebuffer object
Traceback (most recent call last):
  File "/home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py", line 126, in <module>
    test_case.wrap_call(sys.argv[1:])
  File "/home/ling/.cache/paru/clone/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py", line 118, in wrap_call
    self.assertEqual(p.wait(), 0)
  File "/usr/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: -5 != 0
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

106/108 mutter:core+mutter/native/headless / native-headless                                           FAIL            0.78s   exit status 1
107/108 mutter:core+mutter/ref-test/sanity / ref-test-sanity                                           FAIL            0.77s   exit status 1
108/108 mutter:core+mutter/native/persistent-virtual-monitor / native-persistent-virtual-monitor       FAIL            0.77s   exit status 1


Ok:                 105 
Expected Fail:      0   
Fail:               3   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/ling/.cache/paru/clone/mutter-rounded/src/build/meson-logs/testlog.txt
environment: line 1: kill: (46282) - No such process
M 05:11:46.661200        wireplumber ../wireplumber/src/main.c:336:signal_handler: stopped by signal: Terminated
M 05:11:46.662398        wireplumber ../wireplumber/src/main.c:328:on_disconnected: disconnected from pipewire
A connection to the bus can't be made
==> ERROR: A failure occurred in check().
    Aborting...
error: failed to build 'mutter-rounded-41.2-2.1': 
error: packages failed to build: mutter-rounded-41.2-2.1

```

**Comment by yilozt** [comment]
Sorry that I haven't test it with Nvidia driver. The check() stage pass successfully in my Arch Linux with Intel driver. You can use `makepkg --nocheck` to skip check stage if you like.

**Comment by narisuzu** [comment]
thanks. it's help a lot
