### ISSUE TITLE
Support for version 42

### ISSUE THREAD

**Issue by oae** [yilozt/mutter-rounded#53]
Can we get support for mutter 42?

**Comment by Aleksanaa** [comment]
samr request here

**Comment by lolrepeatlol** [comment]
has anyone tried https://github.com/electrikjesus/mutter-rounded ?

**Comment by Aleksanaa** [comment]
When I'm trying to build with mutter commit `f9857cb8bd7af20e819283917ae165fa40c19f07` , test cases 50~114 fail with the same output:
```
(/home/Alexhhh/works/mutter-rounded/src/build/src/tests/clutter/conform/timeline:166823): GLib-GIO-ERROR **: 10:34:50.737: Settings schema 'org.gnome.desktop.privacy' does not contain a key named 'privacy-screen'
Traceback (most recent call last):
  File "/home/Alexhhh/works/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py", line 184, in <module>
    test_case.wrap_call(rest[1:])
  File "/home/Alexhhh/works/mutter-rounded/src/mutter-rounded/src/tests/meta-dbus-runner.py", line 171, in wrap_call
    self.assertEqual(p.wait(), 0)
  File "/usr/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: -5 != 0

```
